# Generated by Django 3.2.25 on 2024-10-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploade_file_on_signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='user_id')),
                ('file', models.FileField(upload_to='files')),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Загруженные файлы',
            },
        ),
        migrations.CreateModel(
            name='Users_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='user_id')),
                ('gost_q', models.CharField(max_length=250, verbose_name='gost_q')),
                ('gost_p', models.CharField(max_length=250, verbose_name='gost_p')),
                ('gost_a', models.CharField(max_length=250, verbose_name='gost_a')),
                ('gost_openkey', models.CharField(max_length=250, verbose_name='gost_openkey')),
                ('gost_secretkey', models.CharField(max_length=250, verbose_name='gost_secretkey')),
            ],
            options={
                'verbose_name': 'Ключи пользователя',
                'verbose_name_plural': 'Ключи пользователей',
            },
        ),
    ]
