# Generated by Django 3.2.25 on 2024-10-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users_key',
            new_name='User_key',
        ),
    ]
