# Generated by Django 3.2.25 on 2024-10-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_users_key_user_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gost_key_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='user_id')),
                ('gost_q', models.CharField(max_length=250, verbose_name='gost_q')),
                ('gost_p', models.CharField(max_length=250, verbose_name='gost_p')),
                ('gost_a', models.CharField(max_length=250, verbose_name='gost_a')),
                ('gost_openkey', models.CharField(max_length=250, verbose_name='gost_openkey')),
                ('gost_secretkey', models.CharField(max_length=250, verbose_name='gost_secretkey')),
            ],
            options={
                'verbose_name': 'Ключи пользователя',
                'verbose_name_plural': 'Ключи пользователей',
            },
        ),
        migrations.DeleteModel(
            name='User_key',
        ),
    ]
